#ifndef ERROR_H
#define ERROR_H

enum err_t
{
    ERR_NONE = 0,

    ERR_FILE_NOT_FOUND,
    ERR_FILE_INVALID_STRUCTURE,
    ERR_FILE_INVALID_DATA,

    ERR_LINKS_INVALID_ALLOC,
    ERR_LINKS_SAME_LINKS,
    ERR_LINKS_INVALID_LINK,

    ERR_POINTS_INVALID_ALLOC,
    ERR_POINTS_SAME_POINTS,

    ERR_MODEL_IS_EMPTY,

    ERR_SCENE_INVALID_ALLOC,

    ERR_ACTION_NO_MODEL,
    ERR_ACTION_INVALID_ENTERED_DATA
};

void error_msg(err_t error);

#endif // ERROR_H
