cmake_minimum_required(VERSION 3.31)
project(lab_03_qt)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)


find_package(Qt6 COMPONENTS
        Core
        Gui
        Widgets
        REQUIRED)

add_executable(lab_03_qt main.cpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/Links/Links.cpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/Links/Links.hpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/Links/LinksIterator.hpp
        src/Exceptions/BaseException.hpp
        src/Exceptions/Figure/LinksException.hpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/Point/Points.cpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/Point/Points.hpp
        src/Exceptions/Figure/PointsException.hpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/Point/PointsIterator.hpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/FigureLP/FigureLP.cpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/FigureLP/FigureLP.hpp
        src/BaseObject/Figure/ConcreteFigure/BaseConcreteFigureLP.hpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/ConcreteFigureLP.cpp
        src/BaseObject/Figure/ConcreteFigure/ConcreteFigureLP/ConcreteFigureLP.hpp
        src/BaseObject/Figure/Figure.cpp
        src/BaseObject/Figure/Figure.hpp
        src/Transforms/Transforms.cpp
        src/Transforms/Transforms.hpp
        src/BaseObject/BaseObject.cpp
        src/BaseObject/BaseObject.hpp
        src/BaseObject/Composite/CompositeObject.cpp
        src/BaseObject/Composite/CompositeObject.hpp
        src/BaseObject/Camera/CameraPTU.cpp
        src/BaseObject/Camera/CameraPTU.hpp
        src/Exceptions/BaseObject/CompositeException.hpp
        src/Managers/SceneManager/Scene/Scene/Scene.cpp
        src/Managers/SceneManager/Scene/Scene/Scene.hpp
        mainwindow.cpp
        mainwindow.hpp
        mainwindow.ui
        src/Exceptions/Scene/SceneException.hpp
        src/Managers/SceneManager/SceneManager.cpp
        src/Managers/SceneManager/SceneManager.hpp
        src/Managers/BaseManager.hpp
        src/Managers/SceneManager/History/BaseHistory.hpp
        src/Managers/SceneManager/History/History.cpp
        src/Managers/SceneManager/History/History.hpp
        src/Facade/Facade.cpp
        src/Facade/Facade.hpp
        src/Builders/BaseBuilder.hpp
        src/Factory/BaseFactory.hpp
        src/Factory/ManagerFactory/ManagerFactory.cpp
        src/Factory/ManagerFactory/ManagerFactory.hpp
        src/Factory/ManagerFactory/ManagerFactoryInterface.hpp
        src/Exceptions/Factory/ManagerFactoryException.hpp
        src/Exceptions/Facade/FacadeException.hpp
        src/Commands/BaseCommand.hpp
        src/Managers/LoadManager/LoadManager.cpp
        src/Managers/LoadManager/LoadManager.hpp
        src/Managers/DrawManager/DrawManager.cpp
        src/Managers/DrawManager/DrawManager.hpp
        src/Managers/TransformManager/TransformManager.cpp
        src/Managers/TransformManager/TransformManager.hpp
        src/Builders/Directors/BaseObjectDirector.hpp
        src/Builders/Readers/BaseReader.hpp
        src/Builders/Readers/LPReaders/BaseLPReader.hpp
        src/Builders/Readers/LPReaders/txt/TXTLPReader.cpp
        src/Builders/Readers/LPReaders/txt/TXTLPReader.hpp
        src/Exceptions/Reader/ReaderException.hpp
        src/Builders/Readers/LPReaders/LPReaderSolution.cpp
        src/Builders/Readers/LPReaders/LPReaderSolution.hpp
        src/Exceptions/Factory/ReaderFactoryException.hpp
        src/Builders/Directors/DirectorSolution.cpp
        src/Builders/Directors/DirectorSolution.hpp
        src/Builders/Directors/FigureDirector/FigureLPDirector.cpp
        src/Builders/Directors/FigureDirector/FigureLPDirector.hpp
        src/Builders/Readers/LPReaders/LPReaderCreator.hpp
        src/Builders/Directors/DirectorCreator.hpp
        src/Exceptions/Directors/DirectorException.hpp
        src/Builders/Builders/FigureLPBuilder/BaseFigureLPBuilder.hpp
        src/Builders/Builders/FigureLPBuilder/FigureLPBuilder.cpp
        src/Builders/Builders/FigureLPBuilder/FigureLPBuilder.hpp
        src/Exceptions/Builders/BuildersException.hpp
        src/Builders/Builders/FigureLPBuilder/FigureLPBuilderCreator.hpp
        src/Builders/Builders/FigureLPBuilder/FigureLPBuilderSolution.cpp
        src/Builders/Builders/FigureLPBuilder/FigureLPBuilderSolution.hpp
        src/Exceptions/Builders/BuildersCreatorException.hpp
        src/Exceptions/Managers/LoadManagerException.hpp
        src/Builders/Directors/CameraDirector/CameraPTUDirector.cpp
        src/Builders/Directors/CameraDirector/CameraPTUDirector.hpp
        src/Builders/Readers/PTUReader/BasePTUReader.hpp
        src/Builders/Readers/PTUReader/cmr/CMRPTUReader.cpp
        src/Builders/Readers/PTUReader/cmr/CMRPTUReader.hpp
        src/Builders/Readers/PTUReader/PTUReaderCreator.hpp
        src/Builders/Readers/PTUReader/PTUReaderSolution.cpp
        src/Builders/Readers/PTUReader/PTUReaderSolution.hpp
        src/Builders/Builders/CameraPTUBuilder/BaseCameraPTUBuilder.hpp
        src/BaseObject/Camera/BaseCameraPTU.hpp
        src/Builders/Builders/CameraPTUBuilder/CameraPTUBuilder.cpp
        src/Builders/Builders/CameraPTUBuilder/CameraPTUBuilder.hpp
        src/Builders/Builders/CameraPTUBuilder/CameraPTUBuilderCreator.hpp
        src/Builders/Builders/CameraPTUBuilder/CameraPTUBuilderSolution.cpp
        src/Builders/Builders/CameraPTUBuilder/CameraPTUBuilderSolution.hpp
        src/BaseObject/Camera/Camera.hpp
        src/Exceptions/Hashes/BaseObjectHashException.hpp
        src/Exceptions/Managers/TransformManager/TransformManagerException.hpp
        src/Exceptions/Managers/TransformManager/TransformActionSolutionException.hpp
        src/Exceptions/Actions/ActionException.hpp
        src/Drawer/Drawer/BaseDrawer.hpp
        src/Drawer/Drawer/QtDrawer.cpp
        src/Drawer/Drawer/QtDrawer.hpp
        src/Visitors/BaseDrawTemplateVisitor.hpp
        src/Visitors/Visitor.hpp
        src/BaseObject/Camera/Camera.cpp
        src/Visitors/Draw/FigureLP/DrawFigureLPVisitor.cpp
        src/Visitors/Draw/FigureLP/DrawFigureLPVisitor.hpp
        src/Commands/FigureCommand/Add/FigureCommandAdd.cpp
        src/Commands/FigureCommand/Add/FigureCommandAdd.hpp
        src/Exceptions/Commands/CommandsException.hpp
        src/Drawer/Factory/Factory/DrawerFactory/QtGraphicsViewFactory.hpp
        src/Drawer/Factory/Factory/AbstractDrawerFactory.hpp
        src/Drawer/Factory/Factory/Pen/BasePen.hpp
        src/Drawer/Factory/Factory/Color/BaseColor.hpp
        src/Drawer/ColorParameters/BaseColorParameters.cpp
        src/Drawer/ColorParameters/BaseColorParameters.hpp
        src/Drawer/ColorParameters/RGBColor.cpp
        src/Drawer/ColorParameters/RGBColor.hpp
        src/Drawer/Factory/BaseDrawerDirector.hpp
        src/Drawer/Factory/Factory/DrawerFactory/QtGraphicsViewFactory.cpp
        src/Exceptions/Drawer/DrawerException.hpp
        src/Drawer/Graphics/BaseGraphics.hpp
        src/Drawer/Graphics/Qt/QtGraphicsScene.cpp
        src/Drawer/Graphics/Qt/QtGraphicsScene.hpp
        src/Drawer/Directors/DrawerDirectorSolution.cpp
        src/Drawer/Directors/DrawerDirectorSolution.hpp
        src/Drawer/Directors/DrawerDirectorCreator.hpp
        src/Drawer/Directors/DrawerDirectorHash.hpp
        src/Drawer/Directors/QtDrawer/QtDrawerDirector.cpp
        src/Drawer/Directors/QtDrawer/QtDrawerDirector.hpp
        src/Drawer/Builders/QtDrawer/BaseQtDrawerBuilder.hpp
        src/Drawer/Builders/BaseDrawerBuilder.hpp
        src/Drawer/Builders/QtDrawer/QtDrawerBuilder.cpp
        src/Drawer/Builders/QtDrawer/QtDrawerBuilder.hpp
        src/Drawer/Factory/Factory/Color/QtColor/QtColor.cpp
        src/Drawer/Factory/Factory/Color/QtColor/QtColor.hpp
        src/Drawer/Factory/Factory/Pen/QtPen/QtPen.cpp
        src/Drawer/Factory/Factory/Pen/QtPen/QtPen.hpp
        src/Visitors/Transform/Move/MoveObjectVisitor.cpp
        src/Visitors/Transform/Move/MoveObjectVisitor.hpp
        src/Visitors/Transform/BaseTransformVisitor.hpp
        src/Visitors/Transform/Rotate/RotateObjectVisitor.cpp
        src/Visitors/Transform/Rotate/RotateObjectVisitor.hpp
        src/Visitors/Transform/Scale/ScaleObjectVisitor.cpp
        src/Visitors/Transform/Scale/ScaleObjectVisitor.hpp
        src/Exceptions/Visitors/VisitorException.hpp
        src/Drawer/Factory/Factory/Pen/QtPen/BaseQtPen.hpp
        src/Drawer/Factory/Factory/Color/QtColor/BaseQtColor.hpp
        src/Visitors/Transform/TransformVisitorSolution.cpp
        src/Visitors/Transform/TransformVisitorSolution.hpp
        src/Visitors/Transform/TransformVisitorHash.hpp
        src/Visitors/Transform/TransformVisitorCreator.hpp
        src/Exceptions/Managers/DrawManagerException.hpp
        src/Visitors/Draw/Solution/DrawVisitorSolution.cpp
        src/Visitors/Draw/Solution/DrawVisitorSolution.hpp
        src/Visitors/Draw/Solution/DrawVisitorHash.hpp
        src/Visitors/Draw/Solution/DrawVisitorCreator.hpp
        src/Commands/FigureCommand/Move/FigureCommandMove.cpp
        src/Commands/FigureCommand/Move/FigureCommandMove.hpp
        src/Commands/FigureCommand/Rotate/FigureCommandRotate.cpp
        src/Commands/FigureCommand/Rotate/FigureCommandRotate.hpp
        src/Commands/FigureCommand/Scale/FigureCommandScale.cpp
        src/Commands/FigureCommand/Scale/FigureCommandScale.hpp
        src/Commands/FigureCommand/Remove/FigureRemoveCommand.cpp
        src/Commands/FigureCommand/Remove/FigureRemoveCommand.hpp
        src/Transforms/Vec.cpp
        src/Transforms/Vec.hpp
        src/Transforms/CameraTransformer/CameraPTU/CameraPTUTransformer.cpp
        src/Transforms/CameraTransformer/CameraPTU/CameraPTUTransformer.hpp
        src/Transforms/CameraTransformer/BaseCameraTransformer.hpp
        src/Exceptions/transform/TransformerException.hpp
        src/Exceptions/transform/VecException.hpp
        src/Transforms/CameraTransformer/Solution/CameraTransformerSolution.cpp
        src/Transforms/CameraTransformer/Solution/CameraTransformerSolution.hpp
        src/Transforms/CameraTransformer/Solution/CameraTransformerHash.hpp
        src/Transforms/CameraTransformer/Solution/CameraTransformerCreator.hpp
        src/Commands/DrawCommand/DrawCommand.cpp
        src/Commands/DrawCommand/DrawCommand.hpp
        src/Commands/DrawCommand/CleanCommand.cpp
        src/Commands/DrawCommand/CleanCommand.hpp
        src/Commands/CameraCommand/Add/CameraCommandAdd.cpp
        src/Commands/CameraCommand/Add/CameraCommandAdd.hpp
        src/GUI/Table.cpp
        src/GUI/Table.hpp
        src/Exceptions/GUI/TableException.hpp
        src/Commands/CameraCommand/Remove/CameraRemoveCommand.cpp
        src/Commands/CameraCommand/Remove/CameraRemoveCommand.hpp
        src/Commands/CameraCommand/Set/CameraSetCommand.cpp
        src/Commands/CameraCommand/Set/CameraSetCommand.hpp
        src/Commands/DrawCommand/BaseDrawCommand.hpp
        src/Commands/CameraCommand/BaseCameraCommand.hpp
        src/Commands/FigureCommand/BaseFigureCommand.hpp
        consts.hpp
        src/Commands/CameraCommand/Move/CameraCommandMove.cpp
        src/Commands/CameraCommand/Move/CameraCommandMove.hpp
        src/Commands/CameraCommand/Rotate/CameraCommandRotate.cpp
        src/Commands/CameraCommand/Rotate/CameraCommandRotate.hpp
)

target_link_libraries(lab_03_qt
        Qt::Core
        Qt::Gui
        Qt::Widgets
)

